export * as Any from './src/Any.js'
export * as Array from './src/Array.js'
export * as String from './src/String.js'
export * as Compose from './src/Compose.js'
export * as Function from './src/Function.js'
export * as Pair from './src/Pair.js'
export * as Tuple from './src/Tuple.js'
export * as Number from './src/Number.js'
export * as Object from './src/Object.js'
export * as Order from './src/Order.js'
export * as Sort from './src/Sort.js'
export * as Schema from './src/Schema.js'
export * as Tap from './src/Tap.js'
export * as Test from './src/Test.js'

export {flow, pipe, identity} from 'effect'
